# Generated by Django 5.1.7 on 2025-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FileField(upload_to="")),
                ("description", models.TextField()),
                ("count", models.IntegerField()),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
